name: Parallel and Conditional Jobs

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - run: echo Run Build
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true
      
      - name: Run JUnit Tests
        run: mvn test -Dmaven.test.failure.ignore=true surefire-report:report

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - run: echo Run Test
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, test] # This job depends on 'build' and 'test' jobs
    steps:
      - run: echo Run Deploy
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - run: echo Finish release'

# Define a conditional job that runs only if 'test' job fails
  notify_failure:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: [test]
    if: failure() # This job runs only if 'test' job fails

    steps:
      - name: Notify team on failure
        run: echo "Test job failed, please investigate."

# Define parallel jobs that run concurrently
  parallel_jobs:
    name: Parallel Jobs
    runs-on: ubuntu-latest
    needs: [build] # These jobs depend on 'build' job

    strategy:
      matrix:
        job1: [1]
        job2: [2]
        job3: [3]
        job4: [4]
        job5: [5]
        job6: [6]
        job7: [7]
        job8: [8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Run parallel job with echo
        run: |
          case ${{ matrix.name }} in
            job1) echo "Running Job 1";;
            job2) echo "Running Job 2";;
            job3) echo "Running Job 3";;
            job4) echo "Running Job 4";;
            job5) echo "Running Job 5";;
            job6) echo "Running Job 6";;
            job7) echo "Running Job 7";;
            job8) echo "Running Job 8";;
          esac
