name: Sequential Jobs Workflow

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Job 1
        run: echo "Running Job 1"

  job2:
    name: Job 2 (Always Skipped)
    runs-on: ubuntu-latest
    if: false  # This ensures the job is always skipped
    needs: job1
    steps:
      - name: Step 1 in Job 2
        run: echo "This should not run"

  job3:
    name: Job 3 (Always Skipped)
    runs-on: ubuntu-latest
    if: false  # This ensures the job is always skipped
    needs: job2
    steps:
      - name: Step 1 in Job 3
        run: echo "This should not run"

  job4:
    name: Job 4
    runs-on: ubuntu-latest
    needs: job3  # Job 4 depends on Job 3
    if: ${{ always() }}  # Ensures that job4 runs no matter what happens with job3
    steps:
      - name: Step 1 in Job 4 - Waiting for 30 seconds
        run: echo "Waiting for 30 seconds..." && sleep 60
      - name: Step 2 in Job 4 - Always Fail
        run: |
          echo "This job is forced to fail."
          exit 1  # Force the job to fail every time
