name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Job 1
        run: echo "Running Job 1"

  job2:
    name: Job 2 (Always Skipped)
    runs-on: ubuntu-latest
    if: false  # This ensures the job is always skipped
    steps:
      - name: Step 1 in Job 2
        run: echo "This should not run"

  job3:
    name: Job 3 (Always Skipped)
    runs-on: ubuntu-latest
    if: false  # This ensures the job is always skipped
    steps:
      - name: Step 1 in Job 3
        run: echo "This should not run"

  job4:
    name: Job 4
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Job 4
        run: echo "Running Job 4"
